[#authoring]
= Document authoring
:page-partial:
:source-highlighter: highlightjs
:icons: font

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]


// Start writing here

Our collaboration workflow is based on GitHub.

We distinguish between:

* *Regular writers*, that <<regular-writers, modify files online>> with the editing interface provided by GitHub.
* *Power writers*, that can <<power-writers, work offline>> and take advantage of the better tooling available (e.g., better spell-checkers and Asciidoc renderers) for desktop editors.

Collaborators that are not part of to the Decidim team can write both online and offline.
See <<external-collaborators>> for more details.

[#regular-writers]
== The easy way: editing on-line

The only other sections you probably need to read are:

* <<asciidoc>>

* <<repo-anatomy>>

[#power-writers]
== Power writers

[#external-collaborators]
== External collaborators

People that does not take part in the core team that develops Decidim can use whatever editing tools they please, including those suggested in this guide for <<regular-writers, regular writers>> and <<power-writers, power writers>>.

The main difference with Decidim Team members is that they are not going to immediately get writing access to Decidim's repositories (maybe never).
They need to https://help.github.com/articles/fork-a-repo/[fork] any repository they want to modify (this does not require any authorization), and interact with the document administrators through https://help.github.com/articles/about-pull-requests/[pull requests].

If you want to collaborate and have not used Git or GitHub before, you can write an email to hola@decidim.com describing the nature of your potential contribution and asking for help.

[#asciidoc]
== Introduction to Asciidoc

=== Asciidoc guidelines

For images use simply the filename, with no directory prefix.

[source, asciidoc]
----
image::IMAGE_FILE_NAME[]
----

[#repo-anatomy]
== Anatomy of a document repository

All document repositories have the following file structure:

[listing]
----
.
├── ca <1>
│   ├── antora.yml
│   └── modules
│       └── ROOT
│           ├── [...]
│           └── pages
│               └── [...]
├── CONTRIBUTING.adoc <2>
├── en <3>
│   ├── antora.yml <4>
│   └── modules
│       └── ROOT
│           ├── assets
│           │   ├── attachments <5>
│           │   └── images <6>
│           ├── _attributes.adoc <7>
│           ├── examples <8>
│           ├── nav.adoc <9>
│           └── pages <10>
│               ├── _attributes.adoc <11>
│               ├── contributing.adoc <12>
│               ├── doc-info.adoc <13>
│               ├── introduction.adoc <14>
│               ├── _partials <15>
│               │   ├── CONTRIBUTING.adoc <16>
│               │   └── README.adoc <17>
│               └── single-page.adoc <18>
├── es <19>
│   ├── antora.yml
│   └── modules
│       └── ROOT
│           ├── [...]
│           └── pages
│               └── [...]
├── LICENSE <20>
└── README.adoc <21>
----
.Most important files and directories
<1> Directory for Catalan version.
Some parts have been elided, but it has the same structure as the English directory.
<3> Directory for the English version.
<5> All files to be downloaded from the website (e.g. PDF files) belong to this directory.
<6> All images (in PNG, SVG or JPEG format) are stored here.
<10> All text is placed in this directory, with an `.adoc` file for every chapter or section.
<14> An example of file for a section or chapter.
<19> Directory for Spanish version, with some parts elided.

.Other files
<2> Authorship criteria and how to contribute to this document.
It is an exact copy of +++<i class="conum" data-value="16"></i><b>16</b>+++, cloned here for easy browsing from GitHub web site.
<8> If you need to include (parts of) code listings in your documentation, put your source code files in this directory.
<15> Put in this directory `.adoc` files that you want only to `include` from other `.adoc` files but without generating a proper page to be independently shown in the documentation website.
<16> Authorship criteria and how to contribute to this document.
You do not need to change this file.
<17> Metadata file: it defines a value for attributes like `{title}`, `{authors}`, `{summary}`, etc. that can be reused all across the document source files.
<19> A file including all other `.adoc` files.
See <<add-ref-to-single-page>>.
<20> The GFDL-1.3 license.
The CC-BY-SA-4.0 license is not included in the repository, it is enough to refer to it in the needed places.
<21> Metadata file.
It is an exact copy of +++<i class="conum" data-value="17"></i><b>17</b>+++, cloned here for easy browsing from GitHub web site.
You need to copy the file again every time +++<i class="conum" data-value="17"></i><b>17</b>+++ is modified.

.For document administrators only
<4> File with configuration information for the xref:administration.adoc#publish[publication of the document] in the documentation site.
<7> Do not touch this file.
<9> Navigation file for xref:administration.adoc#publish[publication of the document] in the documentation site.
<11> Do not touch this file.
<12> You do not need to modify this file.
It can be used in the navigation to show the information contained in +++<i class="conum" data-value="16"></i><b>16</b>+++.
<13> You do not need to modify this file.
It can be used in the navigation to show the information contained in +++<i class="conum" data-value="17"></i><b>17</b>+++.

[#metadata-filling]
== Fill up the metadata

[#create-page]
== Create a new documentation page

Every content we want to see converted to a single web page in https://docs.decidim.org must be written to its own Asciidoc file.
For example, for large documents, at least every chapter or major section must have its own `.adoc` file.
If some section is very long, it can also be split up into smaller source files/web pages.

The smaller the contents, the easier is to reuse them by _including_ in another place.
But it is not necessary to make very small pages either, you still have the possibility to _link_ to any internal header from anywhere in the documentation site.

In order to add a new page to your document, follow the steps in the next sections.

=== (Step {counter:step:1}) Add a new Asciidoc file

The file must be placed in `{LANG}/modules/ROOT/pages`.

The file name should be based upon the title of the section it is going to contain, and must adhere to the following conventions:

* Use only *lower case* letters, numbers, and "-" (hyphen) symbol. Avoid any other character, including punctuation symbols.
* Avoid accents or any other character modifiers.
* Use "-" (hyphen) to separate words.
* The file name must be in *English*.
* Use extension: `.adoc`.
* Optionally reduce the length of the name if name clashes seem improbable.
Take into account that those names will be used also as URLs in the documentation site.

[#file-naming-example]
.Page/section file naming
====
If your section or chapter is named "Deliberative Democracy: How About That?" two possible names would be:

* `deliberative-democracy-how-about-that.adoc`
* `deliberative-democracy.adoc`
====

[IMPORTANT]
--
The same file name *must* be used in all languages if the document has translations.
So, directories `{LANG}/modules/ROOT/pages` should look the same for all values of `{LANG}`, and contained files must be named in English.
--

Copy the following text to the beginning of the file (the same text appears in file `introduction.adoc` from the template), replacing header "Introduction" to the true title of your new section:

[source, asciidoc]
----
= Introduction <1>
:page-partial:

ifndef::env-site,env-github[]
\include::_attributes.adoc[]
endif::[]

\include::{partialsdir}/README.adoc[tag=metadata]

// Start writing here
----
<1> Header to replace.

// // You can remove the line saying:
//
// [source, asciidoc]
// ----
// // Start writing here
// ----
//
// It is useful only to avoid writing just below the last include, without an empty line, // which could cause problems.

[#add-ref-to-single-page]
=== (Step {counter:step:1}) Add a reference to the new file in `single-page.adoc`

The template puts a file `single-page.adoc` in `{LANG}/modules/ROOT/pages`.

Include the newly created `.adoc` file in `single-page.adoc`, following this example:

.Inclusion in `single-page.adoc`
====
If your file is named `deliberative-democracy.adoc`, add a line

[source, asciidoc]
----
\include::deliberative-democracy.adoc[]
----

To `single-page.adoc`.
====

In the file you will find highlighted 3 places where the inclusion is possible.
For regular sections or chapters, use the second slot, and place the new `include` in the correct order with respect the already existing sections.
Leave always a blank line between `include` directives.
The first and third slots are for preambles and appendixes, respectively.

At the beginning you will find a directive

[source, asciidoc]
----
\include::introduction.adoc[]
----

given as example.
Remove it if your document does not have a section called "Introduction".

File `single-page.adoc` has three purposes:

1. During writing, allows to get a rendered preview of the whole document. This only works for desktop, offline editors.
2. It is used to generate a _single page_ view of the document in HTML that can be linked from the documentation site.
3. It is also the base to generate a PDF file.

=== (Step {counter:step:1}) Add a reference to the new file in `nav.adoc`

== When something goes wrong with Git
